-- LMS Platform — jalankan file ini di Supabase: SQL Editor → New query → Run
-- Matikan "Confirm email" di Authentication → Providers → Email agar login lokal lancar.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users (id) on delete cascade,
  name text not null,
  email text unique not null,
  role text not null check (role in ('student', 'admin')),
  created_at timestamptz default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  duration int not null,
  price numeric not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.enrollments (
  student_id bigint not null references public.profiles (id) on delete cascade,
  course_id bigint not null references public.courses (id) on delete cascade,
  status text not null default 'active',
  enrolled_at timestamptz default now(),
  primary key (student_id, course_id)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.profiles (id) on delete cascade,
  course_id bigint not null references public.courses (id) on delete cascade,
  title text not null,
  content text,
  status text not null default 'submitted',
  attachment jsonb,
  score int,
  feedback text,
  submitted_at timestamptz default now(),
  graded_at timestamptz,
  graded_by bigint references public.profiles (id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.profiles (id) on delete cascade,
  items jsonb not null default '[]',
  total numeric not null,
  note text,
  sender_bank text,
  proof jsonb,
  status text not null default 'awaiting_activation',
  created_at timestamptz default now(),
  activated_at timestamptz,
  activated_by bigint references public.profiles (id)
);

create table if not exists public.payment_settings (
  id int primary key default 1,
  instruction text not null
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  bank text not null,
  account_number text not null,
  account_name text not null
);

insert into public.payment_settings (id, instruction)
values (
  1,
  'Transfer sesuai total pembayaran ke salah satu rekening berikut. Lalu unggah bukti transfer agar dosen/admin bisa mengaktifkan kelas.'
)
on conflict (id) do nothing;

insert into public.bank_accounts (bank, account_number, account_name)
select * from (values
  ('BCA', '1234567890', 'LMS Platform'),
  ('Bank Mandiri', '1500012345678', 'LMS Platform')
) as v(bank, account_number, account_name)
where not exists (select 1 from public.bank_accounts);

insert into public.courses (title, description, category, duration, price)
select * from (values
  ('Introduction to Web Development', 'Learn the fundamentals of HTML, CSS, and JavaScript to build modern web applications.', 'programming', 40, 0),
  ('UI/UX Design Principles', 'Master the art of creating beautiful and user-friendly interfaces.', 'design', 30, 0),
  ('Business Management Fundamentals', 'Essential skills for managing teams and projects effectively.', 'business', 35, 150000),
  ('English for Professionals', 'Improve your English communication skills for the workplace.', 'language', 50, 200000)
) as v(title, description, category, duration, price)
where not exists (select 1 from public.courses);

insert into storage.buckets (id, name, public)
values ('assignments', 'assignments', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('payments', 'payments', true)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;
alter table public.assignments enable row level security;
alter table public.orders enable row level security;
alter table public.payment_settings enable row level security;
alter table public.bank_accounts enable row level security;

-- API Next.js memakai service_role (bypass RLS). Policy ini untuk jaga-jaga jika anon key dipakai.
create policy "public read courses" on public.courses for select using (true);
create policy "public read payment" on public.payment_settings for select using (true);
create policy "public read banks" on public.bank_accounts for select using (true);

create policy "public read assignment files" on storage.objects for select using (bucket_id in ('assignments', 'payments'));
create policy "service upload files" on storage.objects for insert with check (bucket_id in ('assignments', 'payments'));
